### PR TITLE
DIG-1653: S3 credential storage

### PR DESCRIPTION
**Pull request by daisieh**
Picks up the authx change to store/get aws credentials. Also adds some endpoints to get and delete existing aws/s3 credentials. Tested in test_aws_credentials in integration tests in https://github.com/CanDIG/CanDIGv2/pull/592

### CODE REVIEW

**Review by OrdiNeu — COMMENTED** [review]
For both the AWS and the S3 credentials -- we store them and return them, but we never seem to check whether or not they correspond to anything valid in the first place. Is there any quick tests we can do to see if they correspond to something real? Or is that impossible because CanDIG might not have access to it?

**Review by OrdiNeu — COMMENTED** [review]
The S3 credential endpoints behave as expected, but before I approve: I notice that there's a split between AWS credentials and S3 credentials, and that we expose the s3 credential endpoints but not the AWS credential endpoints -- is that intentional? Should there be an endpoint in the .yaml for the new `store_aws_credential`/`get_aws_credential`/`remove_aws_credential`?

**Comment by daisieh** [comment]
The S3/AWS names are interchangeable. I could make them more consistent.

**Comment by daisieh** [comment]
> For both the AWS and the S3 credentials -- we store them and return them, but we never seem to check whether or not they correspond to anything valid in the first place. Is there any quick tests we can do to see if they correspond to something real? Or is that impossible because CanDIG might not have access to it?

It is possible, and now that I look closer at the code I wrote in authx, it seems like it tries to create a bucket if the bucket doesn't exist, but that seems like bad behavior for S3 servers we don't control. I wrote it with the assumption that the main use case would be our own Minio server, but that is unlikely to be true in most cases. I'm splitting that out into a separate ticket: https://candig.atlassian.net/browse/DIG-1666

**Review by OrdiNeu — APPROVED** [review]

**Pull request merged**
