### PR TITLE
DIG-1143: Sample DRS objects on htsget ingest

### PR DESCRIPTION
**Pull request by daisieh**
```
source ../CanDIGv2/env.sh
python htsget_s3_ingest.py --samplefile temp/samples.txt --endpoint $MINIO_URL --bucket testhtsget --dataset SYNTHETIC-1 --access $MINIO_ACCESS_KEY --secret $MINIO_SECRET_KEY --clinical_id SAMPLE_REGISTRATION_1
python htsget_file_ingest.py --genomic_id HG02102 --clinical_id SAMPLE_REGISTRATION_2 --file /app/htsget_server/data/files/HG02102.vcf.gz --dataset SYNTHETIC-2
```

You should be able to see the sample drs objects with:
```
curl "http://candig.docker.internal:5080/genomics/ga4gh/drs/v1/objects/SAMPLE_REGISTRATION_2" \
     -H 'Authorization: Bearer <token>'
curl "http://candig.docker.internal:5080/genomics/ga4gh/drs/v1/objects/SAMPLE_REGISTRATION_1" \
     -H 'Authorization: Bearer <token>'
```

### CODE REVIEW

**Comment by OrdiNeu** [comment]
The first one works fine:
```
(candig) fnguyen@fnguyen-worktop:~/Documents/candigv2-ingest$ python htsget_file_ingest.py --genomic_id HG02102 --clinical_id SAMPLE_REGISTRATION_2 --file /app/htsget_server/data/files/HG02102.vcf.gz --d
ataset SYNTHETIC-2                                                                                                                                                                                         
working on HG02102                                                                                                                                                                                         
{'id': 'SYNTHETIC-2', 'drsobjects': ['drs://candig.docker.internal:5080/genomics/HG02102']}                                                                                                                
[                                                                                                                                                                                                          
    {                                                                                                                                                                                                      
        "aliases": [],                                                                                                                                                                                     
        "checksums": [],                                                                                                                                                                                   
        "contents": [                                                                                                                                                                                      
            {                                                                                                                                                                                              
                "drs_uri": [                                                                                                                                                                               
                    "drs://candig.docker.internal:5080/genomics/HG02102.vcf.gz"                                                                                                                            
                ],                                                                                                                                                                                         
                "id": "variant",                                                                                                                                                                           
                "name": "HG02102.vcf.gz"                                                                                                                                                                   
            },                                                                                                                                                                                             
            {                                                                                                                                                                                              
                "drs_uri": [                                                                                                                                                                               
                    "drs://candig.docker.internal:5080/genomics/HG02102.vcf.gz.tbi"                                                                                                                                        ],                                                                                                                                                                                         
                "id": "index",                                                                                                                                                                                             "name": "HG02102.vcf.gz.tbi"                                                                                                                                                               
            }                                                                                                                                                                                              
        ],                                                                                                                                                                                                 
        "created_time": "2023-05-30T13:41:06.322945",                                                                                                                                                      
        "datasets": [                                                                                                                                                                                      
            "SYNTHETIC-2"                                                                                                                                                                                  
        ],                                                                                                                                                                                                 
        "description": "",                                                                                                                                                                                 
        "id": "HG02102",                                                                                                                                                                                   
        "mime_type": "application/octet-stream",                                                                                                                                                           
        "name": "HG02102",                                                                                                                                                                                 
        "self_uri": "drs://candig.docker.internal:5080/genomics/HG02102",                                                                                                                                  
        "size": 0,                                                                                                                                                                                         
        "updated_time": "2023-05-30T13:41:06.322970",                                                                                                                                                      
        "version": "v1"                                                                                                                                                                                    
    },                                                                                               
    {                                                                                                
        "access_methods": [                                                                          
            {                                                                                        
                "access_url": {                                                                      
                    "headers": [],                                                                   
                    "url": "file:///app/htsget_server/data/files/HG02102.vcf.gz.tbi"                                                                                                                       
                },                                                                                   
                "type": "file"                                                                       
            }                                                                                        
        ],                                                                                           
        "aliases": [],                                                                               
        "checksums": [],                                                                             
        "created_time": "2023-05-30T13:41:06.322945",                                                
        "datasets": [],                                                                              
        "description": "",                                                                           
        "id": "HG02102.vcf.gz.tbi",                                                                  
        "mime_type": "application/octet-stream",                                                     
        "name": "HG02102.vcf.gz.tbi",                                                                
        "self_uri": "drs://candig.docker.internal:5080/genomics/HG02102.vcf.gz.tbi",                                                                                                                       
        "size": 0,                                                                                   
        "updated_time": "2023-05-30T13:41:06.322970",                                                
        "version": "v1"                                                                              
    },                                                                                               
    {                                                                                                
        "access_methods": [                                                                          
            {                                                                                        
                "access_url": {                                                                      
                    "headers": [],                                                                   
                    "url": "file:///app/htsget_server/data/files/HG02102.vcf.gz"                                                                                                                           
                },                                                                                   
                "type": "file"                                                                       
            }                                                                                        
        ],                                                                                           
        "aliases": [],                                                                               
        "checksums": [],                                                                             
        "created_time": "2023-05-30T13:41:06.322945",                                                
        "datasets": [],                                                                              
        "description": "",                                                                           
        "id": "HG02102.vcf.gz",                                                                      
        "mime_type": "application/octet-stream",                                                     
        "name": "HG02102.vcf.gz",                                                                    
        "self_uri": "drs://candig.docker.internal:5080/genomics/HG02102.vcf.gz",                                                                                                                           
        "size": 0,                                                                                   
        "updated_time": "2023-05-30T13:41:06.322970",                                                
        "version": "v1"                                                                              
    }                                                                                                
]
(candig) fnguyen@fnguyen-worktop:~/Documents/candigv2-ingest$ curl "http://candig.docker.internal:5080/genomics/ga4gh/drs/v1/objects/SAMPLE_REGISTRATION_2" -H "Authorization: Bearer $TOKEN"
{                                                                                                    
  "aliases": [],                                                                                     
  "checksums": [],                                                                                   
  "contents": [                                                                                      
    {                                                                                                
      "drs_uri": [                                                                                   
        "drs://candig.docker.internal:5080/genomics/HG02102"                                         
      ],                                                                                             
      "id": "genomic",                                                                               
      "name": "HG02102"                                                                              
    }                                                                                                
  ],                                                                                                 
  "created_time": "2023-05-30T13:41:06.322945",                                                      
  "datasets": [],                                                                                    
  "description": "",                                                                                 
  "id": "SAMPLE_REGISTRATION_2",                                                                     
  "mime_type": "application/octet-stream",                                                           
  "name": "SAMPLE_REGISTRATION_2",                                                                   
  "self_uri": "drs://candig.docker.internal:5080/genomics/SAMPLE_REGISTRATION_2",                                                                                                                          
  "size": 0,                                                                                         
  "updated_time": "2023-05-30T13:41:06.322970",                                                      
  "version": "v1"                                                                                    
} 
```

But the first one fails:
```
(candig) fnguyen@fnguyen-worktop:~/Documents/candigv2-ingest$ python htsget_s3_ingest.py --samplefile temp/samples.txt --endpoint $MINIO_URL --bucket testhtsget --dataset SYNTHETIC-1 --access $MINIO_ACCE
SS_KEY --secret $MINIO_SECRET_KEY --clinical_id SAMPLE_REGISTRATION_1
{'endpoint': 'http://candig.docker.internal:9000', 'client': <minio.api.Minio object at 0x7fc03a6efe50>, 'bucket': 'testhtsget', 'access': 'admin', 'secret': 'svG8BvhMlNL7yUOWx3gMoA'}
{'id': 'SYNTHETIC-1', 'drsobjects': []}                                                              
[]                                                                                                   
(candig) fnguyen@fnguyen-worktop:~/Documents/candigv2-ingest$ curl "http://candig.docker.internal:5080/genomics/ga4gh/drs/v1/objects/SAMPLE_REGISTRATION_1"      -H "Authorization: Bearer $TOKEN"
                                                                      
{                                                                                                    
  "message": "No matching object found"                                                              
}
```

Uncertain where to troubleshoot from here.

**Comment by OrdiNeu** [comment]
Docker logs for HTSGet (post-initialization):
```
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 31)
spawned uWSGI worker 1 (pid: 32, cores: 1)
spawned uWSGI worker 2 (pid: 33, cores: 1)
spawned uWSGI worker 3 (pid: 34, cores: 1)
spawned uWSGI worker 4 (pid: 35, cores: 1)
spawned uWSGI http 1 (pid: 36)
[pid: 34|app: 0|req: 1/1] 172.18.0.9 () {38 vars in 1959 bytes} [Tue May 30 13:42:59 2023] POST /ga4gh/drs/v1/datasets => generated 46 bytes in 35 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 0)
[pid: 35|app: 0|req: 1/2] 172.18.0.9 () {38 vars in 1958 bytes} [Tue May 30 13:43:05 2023] POST /ga4gh/drs/v1/objects => generated 709 bytes in 50 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[pid: 34|app: 0|req: 2/3] 172.18.0.9 () {38 vars in 1958 bytes} [Tue May 30 13:43:05 2023] POST /ga4gh/drs/v1/objects => generated 561 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[pid: 34|app: 0|req: 3/4] 172.18.0.9 () {38 vars in 1958 bytes} [Tue May 30 13:43:05 2023] POST /ga4gh/drs/v1/objects => generated 577 bytes in 13 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[2023-05-30 13:43:05,698] WARNING in drs_operations: looking for object SAMPLE_REGISTRATION_2
[pid: 34|app: 0|req: 4/5] 172.18.0.9 () {34 vars in 1947 bytes} [Tue May 30 13:43:05 2023] GET /ga4gh/drs/v1/objects/SAMPLE_REGISTRATION_2 => generated 44 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 110 bytes (1 switches on core 0)
[pid: 33|app: 0|req: 1/6] 172.18.0.9 () {38 vars in 1957 bytes} [Tue May 30 13:43:05 2023] POST /ga4gh/drs/v1/objects => generated 568 bytes in 35 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[W::bcf_hrec_check] Invalid tag name: "cse-hiseq"
[pid: 33|app: 0|req: 2/7] 172.18.0.9 () {34 vars in 2012 bytes} [Tue May 30 13:43:05 2023] GET /htsget/v1/variants/HG02102/index?genome=hg38&force=False&genomic_id=HG02102 => generated 175 bytes in 27914 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[pid: 35|app: 0|req: 2/8] 172.18.0.9 () {38 vars in 1959 bytes} [Tue May 30 13:43:33 2023] POST /ga4gh/drs/v1/datasets => generated 106 bytes in 12 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[pid: 35|app: 0|req: 3/9] 172.18.0.9 () {34 vars in 1930 bytes} [Tue May 30 13:43:33 2023] GET /ga4gh/drs/v1/datasets/SYNTHETIC-2 => generated 106 bytes in 7 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[2023-05-30 13:43:33,703] WARNING in drs_operations: looking for object HG02102
[pid: 35|app: 0|req: 4/10] 172.18.0.9 () {34 vars in 1920 bytes} [Tue May 30 13:43:33 2023] GET /ga4gh/drs/v1/objects/HG02102 => generated 730 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[2023-05-30 13:43:33,720] WARNING in drs_operations: looking for object HG02102.vcf.gz.tbi
[pid: 34|app: 0|req: 5/11] 172.18.0.9 () {34 vars in 1942 bytes} [Tue May 30 13:43:33 2023] GET /ga4gh/drs/v1/objects/HG02102.vcf.gz.tbi => generated 577 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[2023-05-30 13:43:33,733] WARNING in drs_operations: looking for object HG02102.vcf.gz
[pid: 33|app: 0|req: 3/12] 172.18.0.9 () {34 vars in 1934 bytes} [Tue May 30 13:43:33 2023] GET /ga4gh/drs/v1/objects/HG02102.vcf.gz => generated 561 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[2023-05-30 13:45:06,910] WARNING in drs_operations: looking for object SAMPLE_REGISTRATION_2
[pid: 35|app: 0|req: 5/13] 172.18.0.9 () {34 vars in 1928 bytes} [Tue May 30 13:45:06 2023] GET /ga4gh/drs/v1/objects/SAMPLE_REGISTRATION_2 => generated 568 bytes in 7 msecs (HTTP/1.1 200) 3 headers in 104 bytes (1 switches on core 0)
[2023-05-30 13:45:52,596] WARNING in drs_operations: looking for object SAMPLE_REGISTRATION_1
[pid: 35|app: 0|req: 6/14] 172.18.0.9 () {34 vars in 1928 bytes} [Tue May 30 13:45:52 2023] GET /ga4gh/drs/v1/objects/SAMPLE_REGISTRATION_1 => generated 44 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 110 bytes (1 switches on core 0)
[pid: 35|app: 0|req: 7/15] 172.18.0.9 () {38 vars in 1959 bytes} [Tue May 30 13:46:14 2023] POST /ga4gh/drs/v1/datasets => generated 46 bytes in 6 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 0)
[2023-05-30 13:46:17,540] WARNING in drs_operations: looking for object SAMPLE_REGISTRATION_1
[pid: 35|app: 0|req: 8/16] 172.18.0.9 () {34 vars in 1928 bytes} [Tue May 30 13:46:17 2023] GET /ga4gh/drs/v1/objects/SAMPLE_REGISTRATION_1 => generated 44 bytes in 34 msecs (HTTP/1.1 404) 3 headers in 110 bytes (1 switches on core 0)
```

**Comment by OrdiNeu** [comment]
Build status: https://github.com/CanDIG/CanDIGv2/issues/236

**Comment by daisieh** [comment]
Did you happen to have already run integration tests on this setup? If so, you should already have the files in your minio bucket; if not, that might be what is missing. Go to http://candig.docker.internal:9001/browser/testhtsget and see if the files for NA18537.vcf.gz and NA18537.vcf.gz.tbi are there. If not, run make test-integration to install them.

**Review by OrdiNeu — APPROVED** [review]
Oh, yup, that was it. I see how it works now.

**Pull request merged**
