### PR TITLE
DIG-1144: Update to Python 3.12

### PR DESCRIPTION
**Pull request by daisieh**
Picks up new release of clinical_etl as well.

### CODE REVIEW

**Comment by mshadbolt** [comment]
Currently not able to get the tests to pass. If I run in a local 3.12 venv as a standalone, i.e. clone repo, install reqs, run pytest I get the following error:
```
FAILED tests/test_ingest.py::test_htsget_ingest - requests.exceptions.MissingSchema: Invalid URL '/genomics/ga4gh/drs/v1/objects/HG00096.cnv.vcf': No scheme supplied. Perhaps you meant https:///genomics/ga4gh/drs/v1/object...
```

run pytest within the ingest container of my partially running stack after updating the branch and rebuilding I get
```
# pytest
============================================================================================================== test session starts ==============================================================================================================
platform linux -- Python 3.10.13, pytest-7.2.0, pluggy-1.3.0
rootdir: /ingest_app
plugins: requests-mock-1.11.0
collected 8 items / 1 error                                                                                                                                                                                                                     

==================================================================================================================== ERRORS =====================================================================================================================
_____________________________________________________________________________________________________ ERROR collecting tests/test_ingest.py _____________________________________________________________________________________________________
ImportError while importing test module '/ingest_app/tests/test_ingest.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_ingest.py:7: in <module>
    import katsu_ingest
E   ModuleNotFoundError: No module named 'katsu_ingest'
=============================================================================================================== warnings summary ================================================================================================================
clinical_ETL_code/CSVConvert.py:319
clinical_ETL_code/CSVConvert.py:319
clinical_ETL_code/CSVConvert.py:319
clinical_ETL_code/CSVConvert.py:319
  /ingest_app/clinical_ETL_code/CSVConvert.py:319: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
    .applymap(str) \

clinical_ETL_code/CSVConvert.py:320
clinical_ETL_code/CSVConvert.py:320
clinical_ETL_code/CSVConvert.py:320
clinical_ETL_code/CSVConvert.py:320
  /ingest_app/clinical_ETL_code/CSVConvert.py:320: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
    .applymap(lambda x: x.strip()) \

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================================================ short test summary info ============================================================================================================
ERROR tests/test_ingest.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================================= 8 warnings, 1 error in 4.09s ==========================================================================================================
# 
```

entirely possible (and likely) I am doing something wrong though

**Comment by daisieh** [comment]
I haven't tested pytest in the container, so I can take a look at that one, but the first error you got is because I think you need to run `source env.sh` to set the CANDIG_URL environment variable.

**Comment by daisieh** [comment]
I'm also getting the `ModuleNotFoundError: No module named 'katsu_ingest'` error in the container...very weird. Looking into it.

**Comment by daisieh** [comment]
The import error isn't a regression, but still worth fixing...I pushed up a change to add the repo dir to the path for the test file.

**Comment by mshadbolt** [comment]
> I haven't tested pytest in the container, so I can take a look at that one, but the first error you got is because I think you need to run `source env.sh` to set the CANDIG_URL environment variable.

Where does the env.sh come from? I can't see it in the ingest repo? I kinda feel like the tests should work regardless, or is it actually checking the real URL? I thought all the api calls were mocked.

**Comment by mshadbolt** [comment]
Are these lines no longer required now that clinical_ETL is a package? 

```
git submodule update --init --recursive
pip install -r clinical_ETL_code/requirements.txt
```

https://github.com/CanDIG/candigv2-ingest/blob/94e7371f03d7d1e4d98c572c2b18ca380fb185fb/README.md?plain=1#L23C1-L24C50

**Comment by daisieh** [comment]
Sorry, it's the env.sh file in CanDIGv2 repo.

Daisie

**Comment by mshadbolt** [comment]
Confirmed that updated test works within docker in the stack. Is the version on the stack still supposed to be running on 3.10 though?

Confirmed that after sourcing env.sh that the tests pass within ingest running locally

**Comment by daisieh** [comment]
> Confirmed that updated test works within docker in the stack. Is the version on the stack still supposed to be running on 3.10 though?
 
Did you change the value of VENV_PYTHON in your .env file?

**Comment by mshadbolt** [comment]
I did not, will try that and try again

**Comment by mshadbolt** [comment]
updated and all worked as expected

**Review by mshadbolt — APPROVED** [review]
works for me!

**Pull request merged**
